# Use postgres/endurance user/password credentials
version: '3.1'

services:
  react:
    image: react-team3
    build: ./
    ports:
      - 3000:3000

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: endurance

  adminer:
    image: adminer    
    ports:
      - 8080:8080
